# Generated by Django 5.2.1 on 2025-05-12 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
        ('posts', '0002_post_deleted_at_post_is_deleted'),
    ]

    operations = [
    ]
