# Generated by Django 5.2.1 on 2025-05-14 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_like_user_post_deleted_at_post_is_deleted_and_more'),
        ('posts', '0003_merge_20250512_2127'),
    ]

    operations = [
    ]
