# Generated by Django 5.2.1 on 2025-05-26 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_is_active_alter_customuser_is_staff'),
        ('users', '0002_delete_follow_alter_customuser_is_superuser'),
    ]

    operations = [
    ]
