# Generated by Django 5.2.1 on 2025-05-12 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_follow'),
        ('users', '0003_customuser_verification_token'),
    ]

    operations = [
    ]
