# Generated by Django 5.2.1 on 2025-05-12 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_author_comment_content_comment_created_at_and_more'),
        ('comments', '0002_initial'),
    ]

    operations = [
    ]
